=== victoroliveiramarquez/fullxml/Libros.xsd
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="file:///E:/Libros/Libros.xsl"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="libros">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" ref="libro"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="libro">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="obra"/>
				<xs:element ref="fechaPublicacion"/>
				<xs:element ref="precio"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="obra" type="xs:string"/>
	<xs:element name="fechaPublicacion" type="xs:integer"/>
	<xs:element name="precio" type="xs:decimal"/>
</xs:schema>

=== victoroliveiramarquez/fullxml/Libros.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="Libros.xsl"?>
<?xml-stylesheet href="Libros.css"?>
<libros xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///E:/Libros/Libros.xsd">
	<libro>
		<obra>Everyday Italian</obra>
		<fechaPublicacion>2005</fechaPublicacion>
		<precio>29.99</precio>
	</libro>
	<libro>
		<obra>Harry Potter</obra>
		<fechaPublicacion>2005</fechaPublicacion>
		<precio>29.99</precio>
	</libro>
	<libro>
		<obra>XQuery Kick Start</obra>
		<fechaPublicacion>2003</fechaPublicacion>
		<precio>49.99</precio>
	</libro>
	<libro>
		<obra>Learning XML (en)</obra>
		<fechaPublicacion>2003</fechaPublicacion>
		<precio>39.95</precio>
	</libro>
</libros>
